name: build

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: build binary
    permissions: write-all
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: chinese-mini-keyboard-x86_64-unknown-linux
          - os: ubuntu-latest
            osxcross: true
            platform: arm64-apple-darwin20.4
            sdk_version: 11.3
            name: chinese-mini-keyboard-arm64-apple-darwin
          - os: ubuntu-latest
            osxcross: true
            platform: x86_64-apple-darwin20.4
            sdk_version: 11.3
            name: chinese-mini-keyboard-x86_64-apple-darwin
          # - os: windows-latest
          #   name: chinese-mini-keyboard-x86_64-unknown-windows.exe

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - run: sudo apt-get install -y libusb-1.0-0-dev
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - uses: msys2/setup-msys2@v2
        with:
          location: C:/mingw
          update: true
          install: >-
            mingw-w64-x86_64-libusb
        if: ${{ matrix.os == 'windows-latest' }}
      - run: |
          echo 'PKG_CONFIG_PATH=C:/mingw/msys64/mingw64/lib/pkgconfig' >> $env:GITHUB_ENV
          echo 'CGO_CFLAGS=-IC:/mingw/msys64/mingw64/include/libusb-1.0' >> $env:GITHUB_ENV
          echo 'CGO_LDFLAGS="-Wl,-dn,-LC:/mingw/msys64/mingw64/lib"' >> $env:GITHUB_ENV
        if: ${{ matrix.os == 'windows-latest' }}
      - uses: actions/cache@v3
        with:
          path: tools/sigtool
          key: sigtool-${{ hashFiles('tools/sigtool.sh') }}
        if: ${{ matrix.osxcross }}
      - run: ./tools/sigtool.sh
        if: ${{ matrix.osxcross }}
      - uses: actions/cache@v3
        with:
          path: tools/osxcross
          key: osxcross-${{ matrix.platform }}-${{ matrix.sdk_version }}-${{ hashFiles('tools/osxcross.sh') }}
        if: ${{ matrix.osxcross }}
      - run: ./tools/osxcross.sh
        env:
          PLATFORM: ${{ matrix.platform }}
          SDK_VERSION: ${{ matrix.sdk_version }}
        if: ${{ matrix.osxcross }}
      - run: go build -o ${{ matrix.name }} -ldflags "-s -w"
      - run: ./tools/install_name_tool.sh ${{ matrix.name }}
        env:
          PLATFORM: ${{ matrix.platform }}
        if: ${{ matrix.osxcross }}
      - uses: actions/upload-artifact@v3
        with:
          path: ${{ matrix.name }}
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ matrix.name }}
